### ISSUE TITLE
#14 "22 Elm St."

### ISSUE THREAD

**Issue by 95north** [learn-co-curriculum/fewpjs-oo-reviewing-javascript-object-orientation-quiz#3]
class House {
  constructor(address, owner) {
    this.address = address;
    this.owner = owner;
  }
}
 
let house1 = new House('81 Prospect St', 'Alan Turing');
let house2 = new House('11 Broadway', 'Grace Hopper');
house1.owner = 'Ada Lovelace';
house2.address = '1440 G St NW';
Imagine the code above executing. At the end, what is the value of the address property of house1?

Correct Answer: 
‘22 Elm St’

I don't see 22 Elm St. anywhere in the code... I don't think this is right.

**Comment by maxwellbenton** [comment]
Hi @95north,

Thank you for spotting this and providing feedback. We've updated this quiz so that it now includes the correct answer of `81 Prospect St`

Thank you for contributing to a Learn lesson!
